### ISSUE TITLE
[feature request] TLS + websocket + SOCKS

### ISSUE THREAD

**Issue by mo-han** [MetaCubeX/Clash.Meta#259]
目前不支持，我在隔壁发过牢骚了 https://github.com/Dreamacro/clash/issues/2138
要实现这个倒也不难，v2ray 很多年前就简单优雅地支持了这种自定义组合信道，它无非是把 protocol (socks) 和 stream (tls, ws) 两部分给解耦了，配置时两部分相互独立，运行时两个环节拼接起来

**Comment by techblack** [comment]
pr welcome

**Comment by H1JK** [comment]
Since this is not a standard usage of SOCKS, such features may not be supported.

There are many misconceptions about SOCKS:

1. SOCKS is not designed for stealth and can be actively probed even with TLS or username-password authentication etc.

2. SOCKS does not support UoT, and TLS also does not support sending datagram. So UDP packets will be sent directly in plain text and SOCKS-like format, which is an obvious characteristic.

3. SOCKS version 5 protocol-level handshake is 2-RTT at least, and will be higher if you enabled any plugin (like authentication etc). However, Trojan/VLESS/HTTP are 0-RTT on protocol level.

So I think you should use VLESS or Trojan instead.
